CREATE TABLE flights(
    flightID UUID PRIMARY KEY,
    date  VARCHAR(7),
    aircraftTail VARCHAR(10),
    aircraftType VARCHAR(7),
    mission VARCHAR(50),
    missionStatement TEXT,
    route VARCHAR(50),
    etd VARCHAR(5),
    ete VARCHAR(5),
    flightConditions VARCHAR(20),
    pc VARCHAR(30),
    pcRisk VARCHAR(2),
    pcSeat VARCHAR(10),
    pi VARCHAR(30),
    piRisk VARCHAR(2),
    piSeat VARCHAR(10),
    nrcm1 VARCHAR(30),
    nrcm1Risk VARCHAR(2),
    nrcm2 VARCHAR(30),
    nrcm2Risk VARCHAR(2),
    nrcm3 VARCHAR(30),
    nrcm3Risk VARCHAR(2),
    pcHoursTotal INTEGER,
    pcHoursNG INTEGER,
    pc25HoursInAO BOOLEAN,
    piHoursTotal INTEGER,
    piHoursNG INTEGER,
    pi25HoursInAO BOOLEAN,
    nrcm1HoursTotal INTEGER,
    nrcm1HoursNG INTEGER,
    nrcm125HoursInAO BOOLEAN,
    nrcm2HoursTotal INTEGER,
    nrcm2HoursNG INTEGER,
    nrcm225HoursInAO BOOLEAN,
    nrcm3HoursTotal INTEGER,
    nrcm3HoursNG INTEGER,
    nrcm325HoursInAO BOOLEAN,
    aircrewRiskMitigation TEXT,
    aircrewInitialRisk VARCHAR(2),
    aircrewMitigatedRisk VARCHAR(2),
    airAssault VARCHAR(10),
    AH64AttackReconSecurity VARCHAR(10),
    MEDEVAC VARCHAR(10),
    CASEVAC VARCHAR(10),
    FARP VARCHAR(10),
    multiship VARCHAR(2),
    mixedMultiShip VARCHAR(10),
    MTFGeneralTraining VARCHAR(10),
    dartOneTimeFlight VARCHAR(2),
    blackout VARCHAR(10),
    waterBucket VARCHAR(10),
    paradrops VARCHAR(10),
    rappelSpiesFries VARCHAR(10),
    externalLoads VARCHAR(10),
    airmovementVIP VARCHAR(10),
    continuation VARCHAR(10),
    CEFS VARCHAR(10),
    fatCow VARCHAR(10),
    crossCountryBorder VARCHAR(10),
    terrainFlight VARCHAR(10),
    mountainOperations VARCHAR(10),
    overwaterOperations VARCHAR(10),
    pinnacleOperations VARCHAR(10),
    urbanOperations VARCHAR(2),
    confinedOperations VARCHAR(2),
    OGEwithin10 VARCHAR(10),
    IGEwithin10 VARCHAR(10),
    OGEwithin5 VARCHAR(10),
    IGEwithin5 VARCHAR(10),
    progessionEvaluationEPs VARCHAR(10),
    IFRSimulatedIMC VARCHAR(10),
    CBRNE VARCHAR(10),
    nonLiveHoist VARCHAR(10),
    liveHoist VARCHAR(10),
    combatManueveringFlight VARCHAR(10),
    gunneryLiveFire VARCHAR(10),
    CALFEX VARCHAR(10),
    AMS VARCHAR(10),
    pcGt90 VARCHAR(10),
    pcGt60 VARCHAR(10),
    pcGt30 VARCHAR(10),
    piGt90 VARCHAR(10),
    piGt60 VARCHAR(10),
    piGt30 VARCHAR(10),
    nrcm1Gt90 VARCHAR(10),
    nrcm1Gt60 VARCHAR(10),
    nrcm1Gt30 VARCHAR(10),
    nrcm2Gt90 VARCHAR(10),
    nrcm2Gt60 VARCHAR(10),
    nrcm2Gt30 VARCHAR(10),
    nrcm3Gt90 VARCHAR(10),
    nrcm3Gt60 VARCHAR(10),
    nrcm3Gt30 VARCHAR(10),
    hoistGt90 VARCHAR(10),
    hoistGt60 VARCHAR(10),
    hoistGt30 VARCHAR(10),
    specificGt12 VARCHAR(10),
    specific2to12 VARCHAR(10),
    specificLt2 VARCHAR(10),
    vagueGt12 VARCHAR(10),
    vague2to12 VARCHAR(10),
    vagueLt2 VARCHAR(10),
    missionRiskMitigation TEXT,
    missionInitialRisk VARCHAR(2),
    missionMitigatedRisk VARCHAR(2),
    gt1000 VARCHAR(10),
    lt1000 VARCHAR(10),
    lt700 VARCHAR(10),
    lt500 VARCHAR(10),
    gt3 VARCHAR(10),
    gt2 VARCHAR(10),
    gt1 VARCHAR(10),
    lt1 VARCHAR(10),
    altRequired BOOLEAN,
    gt25IllumAndgt30degrees VARCHAR(10),
    lt25IllumAndlt30degrees VARCHAR(10),
    gt25IllumAndgt30degreesLimitedLighting VARCHAR(10),
    windGt30 VARCHAR(10),
    windGt30Hoist VARCHAR(10),
    gustSpreadGt20 VARCHAR(10),
    forecastThunderstorms VARCHAR(10),
    modTurbulenceIcing VARCHAR(10),
    oatNegative10Positive30 VARCHAR(10),
    weatherRiskMitigation TEXT,
    weatherInitialRisk VARCHAR(2),
    weatherMitigatedRisk VARCHAR(2),
    finalRiskMitigation TEXT,
    finalMitigatedRisk VARCHAR(2),
    briefer VARCHAR(50),
    brieferComment TEXT,
    brieferCommentDate VARCHAR(20),
    approver VARCHAR(50),
    approverComment TEXT,
    approverCommentDate VARCHAR(20),
    greatestRisk VARCHAR(50)
);


INSERT INTO flights(
    flightID,
    date,
    aircraftType,
    aircraftTail,
    mission,
    missionStatement,
    route,
    etd,
    ete,
    flightConditions,
    pc,
    pcRisk,
    pcSeat,
    pi,
    piRisk,
    piSeat,
    nrcm1,
    nrcm1Risk,
    nrcm2,
    nrcm2Risk,
    nrcm3,
    nrcm3Risk,
    pcHoursTotal,
    pcHoursNG,
    pc25HoursInAO,
    piHoursTotal,
    piHoursNG,
    pi25HoursInAO,
    nrcm1HoursTotal,
    nrcm1HoursNG,
    nrcm125HoursInAO,
    nrcm2HoursTotal,
    nrcm2HoursNG,
    nrcm225HoursInAO,
    nrcm3HoursTotal,
    nrcm3HoursNG,
    nrcm325HoursInAO,
    aircrewRiskMitigation,
    aircrewInitialRisk,
    aircrewMitigatedRisk,
    airAssault,
    AH64AttackReconSecurity,
    MEDEVAC,
    CASEVAC,
    FARP,
    multiship,
    mixedMultiShip,
    MTFGeneralTraining,
    dartOneTimeFlight,
    blackout,
    waterBucket,
    paradrops,
    rappelSpiesFries,
    externalLoads,
    airmovementVIP,
    continuation,
    CEFS,
    fatCow,
    crossCountryBorder,
    terrainFlight,
    mountainOperations,
    overwaterOperations,
    pinnacleOperations,
    urbanOperations,
    confinedOperations,
    OGEwithin10,
    IGEwithin10,
    OGEwithin5,
    IGEwithin5,
    progessionEvaluationEPs,
    IFRSimulatedIMC,
    CBRNE,
    nonLiveHoist,
    liveHoist,
    combatManueveringFlight,
    gunneryLiveFire,
    CALFEX,
    AMS,
    pcGt90,
    pcGt60,
    pcGt30,
    piGt90,
    piGt60,
    piGt30,
    nrcm1Gt90,
    nrcm1Gt60,
    nrcm1Gt30,
    nrcm2Gt90,
    nrcm2Gt60,
    nrcm2Gt30,
    nrcm3Gt90,
    nrcm3Gt60,
    nrcm3Gt30,
    hoistGt90,
    hoistGt60,
    hoistGt30,
    specificGt12,
    specific2to12,
    specificLt2,
    vagueGt12,
    vague2to12,
    vagueLt2,
    missionRiskMitigation,
    missionInitialRisk,
    missionMitigatedRisk,
    gt1000,
    lt1000,
    lt700,
    lt500,
    gt3,
    gt2,
    gt1,
    lt1,
    altRequired,
    gt25IllumAndgt30degrees,
    lt25IllumAndlt30degrees,
    gt25IllumAndgt30degreesLimitedLighting,
    windGt30,
    windGt30Hoist,
    gustSpreadGt20,
    forecastThunderstorms,
    modTurbulenceIcing,
    oatNegative10Positive30,
    weatherRiskMitigation,
    weatherInitialRisk,
    weatherMitigatedRisk,
    finalRiskMitigation,
    finalMitigatedRisk,
    briefer,
    brieferComment,
    brieferCommentDate,
    approver,
    approverComment,
    approverCommentDate,
    greatestRisk
)VALUES(
    "650a9954-ebfe-475c-8a2c-be0858fc54cd",
    "28AUG23",
    "HH60M",
    "20-20130",
    "NRCM RL Progression",
    "NRCM RL Progression in local area.",
    "ETIC-ETIC",
    "15:00",
    "2.0",
    "1",
    "CW2 Brandes",
    "M",
    "Left",
    "CW2 Rappisi",
    "M",
    "Right",
    "SSG Stewart",
    "L",
    "SPC Dilick",
    "M",
    "",
    "L",
    "400.3",
    "103.3",
    true,
    "273.1",
    "64.5",
    true,
    "1579.7",
    "480.4",
    true,
    "176.6",
    "69.3",
    true,
    "",
    "",
    "",
    "Aircrew will brief all tasks during crew brief and again prior to execution to ensure shared understanding prior to implementation.",
    "M",
    "L",
    "",
    "",
    "",
    "",
    "",
    "D",
    "",
    "D",
    "",
    "",
    "",
    "",
    "",
    "D",
    "",
    "",
    "L",
    "L",
    "D",
    "",
    "",
    "",
    "",
    "D",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "true",
    "",
    "",
    "CEFS Operations will be discussed in detail to ensure progressing NRCM understands how to adjust tasks/scan sectors prior to flight.",
    "L",
    "L",
    "D",
    "",
    "",
    "",
    "",
    "",
    "D",
    "",
    "",
    "",
    "true",
    "",
    "",
    "",
    "Will not below above minimums.",
    "L",
    "L",
    "M",
    "All actions will be done IAW Task 1070. Aircrew will mutually acknowledge the real-world emergency and training will stop until the emergency is complete.",
    "L",
    "",
    "- Call Weather - Review Task 1070 - Conduct simulated EPs in downwind leg to ensure FI has sufficient time.",
    "",
    "",
    "Fly safe!",
    "",
    "",
    "Crew efficiency during a real-world emergency."
)