const flights = [
    {
        mission: 'ATM Cont',
        missionStatement: 'NG Reset in local area. Going to fly low and fast, definitely not going to flip the aircraft on its side over the trees.',
        date: '1AUG23',
        route: 'ETIC-ETIC',
        aircraftType: 'HH60M',
        aircraftTail: '20130',
        pc: 'CPT Reynolds',
        pcSeat: 'L',
        pi: 'CW3 Vegas',
        piSeat: 'R',
        nrcm1: 'SGT Jules',
        nrcm2: 'SPC Wallace',
        nrcm3: null,
        flightConditions: '1, 3, 6',
        etd: '2030',
        ete: '0100',
        pcHoursTotal: 463.9,
        pcHoursNG: 105.2,
        pc25HoursInAO: true,
        piHoursTotal: 2351.0,
        piHoursNG: 384.2,
        pi25HoursInAO: true,
        nrcm1HoursTotal: 399.9,
        nrcm1HoursNG: 152.7,
        nrcm125HoursInAO: true,
        nrcm2HoursTotal: 150.1,
        nrcm2HoursNG: 200.2,
        nrcm225HoursInAO: true,
        nrcm3HoursTotal: 611.8,
        nrcm3HoursNG: 205.4,
        nrcm325HoursInAO: true,
        aircrewInitialRisk: 'M',
        aircrewRiskMitigation: 'PC with >180 hours in AO paired with PC/MTP. Low risk NRCMs paired with Moderate risk PC. CE/MO have >50 hours in AO & are familiar with route to be flown.',
        aircrewMitigatedRisk: 'L',
        hundredHoursinLast30Days: false,
        hundredtenHoursinLast30Days: false,
        lessthan10HoursRest: false,
        lessthan8HoursRest: false,
        extensionInLast24Hours: false,
        twoExtensionsInLast48Hours: false,
        missionCompleteInLastThird: false,
        airAssault: null,
        AH64AttackReconSecurity: null,
        medevacCasevac: 'D NG',
        multiship: null,
        mixedMultiShip: null,
        MTFGeneralTraining: null,
        dartOneTimeFlight: null,
        blackout: null,
        waterBucket: null,
        paradrops: null,
        rappelSpiesFries: null,
        externalLoads: null,
        airmovementVIP: null,
        continuation: null,
        CEFS: 'D NG',
        fatCow: null,
        terrainFlight: 'D NG',
        mountainOperations: null,
        overwaterOperations: null,
        pinnacleOperations: null,
        urbanOperations: null,
        confinedOperations: 'D NG',
        OGEwithin10: null,
        IGEwithin10: null,
        OGEwithin5: null,
        IGEwithin5: null,
        progessionEvaluationEPs: null,
        IFRSimulatedIMC: null,
        CBRNE: null,
        nonLiveHoist: 'D NG',
        liveHoist: 'D NG',
        combatManueveringFlight: null,
        gunneryLiveFire: null,
        CALFEX: null,
        AMS: null,
        pcGt90: null,
        pcGt60: null,
        pcGt30: null,
        piGt90: null,
        piGt60: null,
        piGt30: null,
        nrcm1Gt90: null,
        nrcm1Gt60: null,
        nrcm1Gt30: null,
        nrcm2Gt90: null,
        nrcm2Gt60: null,
        nrcm2Gt30: null,
        nrcm3Gt90: null,
        nrcm3Gt60: null,
        nrcm3Gt30: null,
        hoistGt90: null,
        hoistGt60: null,
        hoistGt30: null,
        specificGt12: null,
        specific2to12: null,
        specificLt2: null,
        vagueGt12: 'D',
        vague2to12: null,
        vagueLt2: null,
        missionInitialRisk: 'M*',
        missionRiskMitigation: 'Crew will use exterior lighting as required.',
        missionMitigatedRisk: 'M*',
        gt25IllumAndgt30degrees: true,
        lt25IllumAndlt30degrees: false,
        gt25IllumAndgt30degreesLimitedLighting: false,
        windGt30: null,
        windGt30Hoist: null,
        gustSpreadGt20: null,
        forecastThunderstorms: null,
        modTurbulenceIcing: null,
        oatNegative10Positive30: null,
        altRequired: false,
        gt1000: 'D NG',
        lt1000: null,
        lt700: null,
        lt500: null,
        gt3: null,
        gt2: null,
        gt1: null,
        lt1: null,
        weatherInitialRisk: 'H',
        weatherRiskMitigation: 'Crew will use exterior lighting as required.',
        weatherMitigatedRisk: 'M',
        initialRisk: 'M*',
        finalMitigatedRisk: 'M*',
        greatestRisk: 'Combat maneuvering flight in NG conditions.',
        finalRiskMitigation: 'Detailed table talk and brief will be conducted by crew prior to flight.',
        briefer: 'CW2 Trinity',
        brieferComment: 'Update NOTAMS for the restricted area. Call base ops to deconflict for landing at the hospital pad. Brief go-arounds and escape routes prior to approaches.',
        brieferCommentDate: '15JUL23 10:10',
        approver: 'CPT Neo',
        approverComment: 'Fly safe!',
        approverCommentDate: '17JUL23 13:10',
    },
    {
        date: "11SEP23",
        aircraftType: "HH60M",
        aircraftTail: "20-20128",
        mission: "CONT TNG",
        missionStatement: "NRCM RL Progression in local area.",
        route: "ETIC-ETIC",
        etd: "15:00",
        ete: "1.5",
        flightConditions: "1",
        pc: "CPT Reynolds",
        pcSeat: "Left",
        pi: "CPT Smith",
        piSeat: "Right",
        nrcm1: "SGT Daniels",
        nrcm2: "SGT Martinez",
        nrcm3: "",
        aircrewRiskMitigation: "air crew brief",
        aircrewInitialRisk: "L",
        aircrewMitigatedRisk: "L",
        airAssault: "",
        AH64AttackReconSecurity: "",
        medevacCasevac: "",
        multiship: "",
        mixedMultiShip: "",
        MTFGeneralTraining: "",
        dartOneTimeFlight: "",
        blackout: "",
        waterBucket: "",
        paradrops: "",
        rappelSpiesFries: "",
        externalLoads: "",
        airmovementVIP: "",
        continuation: "D",
        CEFS: "D",
        fatCow: "",
        terrainFlight: "D",
        mountainOperations: "",
        overwaterOperations: "",
        pinnacleOperations: "",
        urbanOperations: "",
        confinedOperations: "",
        OGEwithin10: "",
        IGEwithin10: "",
        OGEwithin5: "",
        IGEwithin5: "",
        progessionEvaluationEPs: "",
        IFRSimulatedIMC: "D",
        CBRNE: "",
        nonLiveHoist: "D",
        liveHoist: "",
        combatManueveringFlight: "",
        gunneryLiveFire: "",
        CALFEX: "",
        AMS: "",
        pcGt90: "",
        pcGt60: "",
        pcGt30: "",
        piGt90: "",
        piGt60: "",
        piGt30: "",
        nrcm1Gt90: "",
        nrcm1Gt60: "",
        nrcm1Gt30: "",
        nrcm2Gt90: "",
        nrcm2Gt60: "",
        nrcm2Gt30: "",
        nrcm3Gt90: "",
        nrcm3Gt60: "",
        nrcm3Gt30: "",
        hoistGt90: "",
        hoistGt60: "",
        hoistGt30: "",
        specificGt12: "",
        specific2to12: "",
        specificLt2: "",
        vagueGt12: "D",
        vague2to12: "",
        vagueLt2: "",
        missionRiskMitigation: "Check range NOTAMs",
        missionInitialRisk: "M",
        missionMitigatedRisk: "L",
        gt1000: "D",
        lt1000: "",
        lt700: "",
        lt500: "",
        gt3: "D",
        gt2: "",
        gt1: "",
        lt1: "",
        altRequired: "",
        gt25IllumAndgt30degrees: "",
        lt25IllumAndlt30degrees: "",
        gt25IllumAndgt30degreesLimitedLighting: "",
        windGt30: "",
        windGt30Hoist: "D",
        gustSpreadGt20: "",
        forecastThunderstorms: "",
        modTurbulenceIcing: "",
        oatNegative10Positive30: "",
        weatherRiskMitigation: "Will check weather",
        weatherInitialRisk: "H",
        weatherMitigatedRisk: "M",
        finalRiskMitigation: "hoist check",
        finalMitigatedRisk: "M",
        greatestRisk: "Hoist",
        brieferComment: "Comments from MBO",
        approverComment: "Comments from FMAA"
    }


]
export default flights